version: '3.8'
services:
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"

  casino-server:
    build: .
    container_name: casino
    ports:
      - "7000:7000"
    depends_on:
      - redis

